spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# spring.sql.init.mode=always asegura que los scripts schema.sql y data.sql se ejecuten siempre al iniciar.
# Esto es útil para desarrollo y pruebas para mantener la base de datos en un estado consistente.
spring.sql.init.mode=always