-- Schema especifico para tests con H2 en memoria.
-- Usamos sintaxis SQL estandar (GENERATED BY DEFAULT AS IDENTITY) que entienden
-- tanto H2 como PostgreSQL. Asi evitamos depender de modos especiales.

DROP TABLE IF EXISTS experiences;
DROP TABLE IF EXISTS educations;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS personal_info;

CREATE TABLE personal_info
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100) NOT NULL,
    title               VARCHAR(255) NOT NULL,
    profile_description TEXT         NOT NULL,
    profile_image_url   VARCHAR(500),
    years_of_experience INT,
    email               VARCHAR(255),
    phone               VARCHAR(50),
    linkedin_url        VARCHAR(500),
    github_url          VARCHAR(500)
);

CREATE TABLE skills
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100) NOT NULL,
    level_percentage INT,
    icon_class       VARCHAR(100),
    personal_info_id BIGINT       NOT NULL,
    CONSTRAINT fk_skill_personal_info
        FOREIGN KEY (personal_info_id)
            REFERENCES personal_info (id)
            ON DELETE CASCADE
);

CREATE TABLE educations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    degree           VARCHAR(255) NOT NULL,
    institution      VARCHAR(255) NOT NULL,
    start_date       DATE         NOT NULL,
    end_date         DATE,
    description      TEXT,
    personal_info_id BIGINT       NOT NULL,
    CONSTRAINT fk_education_personal_info
        FOREIGN KEY (personal_info_id)
            REFERENCES personal_info (id)
            ON DELETE CASCADE
);

CREATE TABLE experiences
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title        VARCHAR(255) NOT NULL,
    company_name     VARCHAR(255) NOT NULL,
    start_date       DATE         NOT NULL,
    end_date         DATE,
    description      TEXT,
    personal_info_id BIGINT       NOT NULL,
    CONSTRAINT fk_experience_personal_info
        FOREIGN KEY (personal_info_id)
            REFERENCES personal_info (id)
            ON DELETE CASCADE
);
